### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by carolmascarenhas** [heisenburger/typora-theme-refine#1]
Hi, what fonts did you use in interface? I want that my interface would be the same shown in the prints.

**Comment by heisenburger** [comment]
Hello! Here's the fontstack I'm using:
```
  --ff-sans: -apple-system, BlinkMacSystemFont, "Helvetica Neue", "Helvetica", 
    "Arial", "Roboto", "Ubuntu", "Segoe UI", "Fira Sans", "Droid Sans", 
    sans-serif;
  --ff-serif: "Adobe Caslon Pro", "Goudy Old Style", 
    "Athelas", "Californian FB", "Georgia Pro", Georgia,
    serif;
  --ff-disp: "Questa Grande", "QuestaGrande", "Didot", "Didonesque", serif;
--ff-disp-sm: "Questa", "Georgia Pro", Georgia, serif;
```

In the screenshots, here are the fonts that are being rendered:

Heading 1: [Questa Grande](https://fonts.adobe.com/foundries/the-questa-project)
Heading 2: [SF Pro](https://developer.apple.com/fonts/)
Heading 3: [Athelas](https://fonts.adobe.com/fonts/athelas)

Hope that helps!

**Comment by heisenburger** [comment]
Let me know if you need anything else :)
